:tada: Working prototype

diff --git a/create b/create
--- a/create
+++ b/create
@@ -17,16 +17,26 @@ true && return 1 2>/dev/null # exit if sourced
 cd -- "$PWD" || exit "$?"
 IFS=$'\n'
 set -o errexit -o nounset -o pipefail || exit 1
+function print_color() {
+	local color
+	color="$1"
+	shift
+	printf "\x1b[38;5;${color}m::\x1b[0m %s\n" "$@"
+}
 function print() {
-	printf "\x1b[38;5;14m::\x1b[0m %s\n" "$@"
+	print_color 14 "$@"
 	return 0
 }
 function debug() {
-	printf "\x1b[38;5;13m::\x1b[0m %s\n" "$@"
+	print_color 13 "$@"
+	return 0
+}
+function warn() {
+	print_color 11 "$@" >&2
 	return 0
 }
 function error() {
-	printf "\x1b[38;5;9m::\x1b[0m %s\n" "$@" >&2
+	print_color 9 "$@" >&2
 	return 1
 }
 function print_raw() {
@@ -135,22 +145,33 @@ function ensure_does_not_exist() {
 function install_packages() {
 	local root
 	local -A packages
+	local -A force_packages
 	root="$1"
 	shift
 	if [[ -z "$root" || ! -d "$root" ]]; then
 		error "Invalid root directory"
 	fi
 	packages=()
+	force_packages=()
 	for i in "$@"; do
 		if [[ -z "$i" ]]; then
 			continue
 		fi
-		packages["$i"]=1
+		if [[ "${i:0:1}" == "!" ]]; then
+			force_packages["${i:1}"]=1
+			packages["${i:1}"]=1
+			continue
+		else
+			force_packages["$i"]=0
+			packages["$i"]=1
+		fi
 	done
 	IFS=$'\n'
 	if [[ -d "$root"/var/lib/pacman ]]; then
 		while IFS= read -r line; do
-			unset "packages[$line]"
+			if [[ "${force_packages[$line]}" == "0" ]]; then
+				unset -v "packages[$line]"
+			fi
 		done < <(pacman --root "$root" -Qq - <<<"${!packages[*]}" 2>/dev/null)
 	fi
 	if [[ ${#packages[@]} -eq 0 ]]; then
@@ -162,29 +183,34 @@ function install_packages() {
 }
 check_installed mksquashfs chroot grub-install mkdir ln cp mv unlink basestrap pacman printf grub-mkrescue awk mkfs.ext4 tar
 check_root
-ensure_exists grub.cfg
-ensure_exists update-dracut
 
 configure
-
 BOOT="$ROOT/boot"
 ROOTFS="rootfs.img"
-confirm "Script settings: " \
-	"  Root directory is at '$ROOT'." \
-	"  Root filesystem image is at '$ROOTFS'." \
-	"  Output ISO file will be saved to '$ISO'." \
-	"  ISO label is '$VOLID'." \
-	"Recovery environment options:" \
-	"  Language is '$INSTALL_LANG'." \
-	"  Language encoding is '$INSTALL_LANG_ENC'." \
-	"  Keymap is '$INSTALL_KEYMAP'." \
-	"  Timezone is '$INSTALL_TZ'." \
-	"  User is '$INSTALL_USER'." \
-	"  Font is '$INSTALL_FONT'." \
-	"Continue?"
+function clean() {
+	delete_file "$ISO"
+	delete_file "$ROOTFS"
+}
+function make() {
+	ensure_exists grub.cfg
+	ensure_exists update-dracut
 
-if false; then
-	PACKAGES=(base base-devel dinit dbus-dinit seatd-dinit nano neovim git curl wget sudo linux linux-firmware intel-ucode amd-ucode mandoc man-pages efibootmgr grub dracut os-prober networkmanager-dinit less terminus-font baobab gdm-dinit gnome-session gnome-backgrounds gnome-calculator gnome-calendar gnome-characters gnome-clocks gnome-color-manager gnome-console gnome-control-center gnome-font-viewer gnome-keyring gnome-menus gnome-settings-daemon gnome-shell gnome-shell-extensions gnome-software gnome-system-monitor gnome-text-editor gnome-user-docs gnome-user-share gvfs loupe nautilus simple-scan snapshot sushi xdg-desktop-portal-gnome xdg-user-dirs-gtk firefox okular squashfs-tools device-mapper gparted dosfstools jfsutils f2fs-tools btrfs-progs exfatprogs ntfs-3g reiserfsprogs udftools xfsprogs nilfs-utils polkit gpart mtools xorg-xhost)
+	confirm "Script settings: " \
+		"  Root directory is at '$ROOT'." \
+		"  Root filesystem image is at '$ROOTFS'." \
+		"  Output ISO file will be saved to '$ISO'." \
+		"  ISO label is '$VOLID'." \
+		"Recovery environment options:" \
+		"  Language is '$INSTALL_LANG'." \
+		"  Language encoding is '$INSTALL_LANG_ENC'." \
+		"  Keymap is '$INSTALL_KEYMAP'." \
+		"  Timezone is '$INSTALL_TZ'." \
+		"  User is '$INSTALL_USER'." \
+		"  Font is '$INSTALL_FONT'." \
+		"Change these settings in the script if needed." \
+		"Continue?"
+
+	PACKAGES=(base base-devel dinit-base dinit dinit-rc dbus-dinit seatd-dinit nano neovim git curl wget sudo linux linux-firmware intel-ucode amd-ucode mandoc man-pages efibootmgr grub dracut os-prober networkmanager-dinit less terminus-font baobab gdm-dinit gnome-session gnome-backgrounds gnome-calculator gnome-characters gnome-clocks gnome-color-manager gnome-console gnome-control-center gnome-font-viewer gnome-keyring gnome-menus gnome-settings-daemon gnome-shell gnome-shell-extensions gnome-software gnome-system-monitor gnome-text-editor gnome-user-docs gnome-user-share gvfs loupe nautilus simple-scan snapshot sushi xdg-desktop-portal-gnome xdg-user-dirs-gtk firefox okular squashfs-tools device-mapper gparted dosfstools jfsutils f2fs-tools btrfs-progs exfatprogs ntfs-3g reiserfsprogs udftools xfsprogs nilfs-utils polkit gpart mtools xorg-xhost qemu-guest-agent-dinit usbutils)
 	# TODO: gparted optional dependencies
 	create_dir "$ROOT"
 	print "Installing packages"
@@ -194,7 +220,7 @@ if false; then
 	print_raw "LANG=$INSTALL_LANG" >"$ROOT/etc/locale.conf"
 	print_raw "KEYMAP=$INSTALL_KEYMAP" "FONT=$INSTALL_FONT" >"$ROOT/etc/vconsole.conf"
 	print_raw "%wheel ALL=(ALL) ALL" >"$ROOT"/etc/sudoers.d/wheel
-	print_raw 'add_dracutmodules+=" dmsquash-live "' 'install_items+=" /usr/bin/lsblk /usr/bin/lsmod "' >"$ROOT"/etc/dracut.conf.d/02-squashfs.conf
+	print_raw '[daemon]' 'AutomaticLoginEnable=True' "AutomaticLogin=$USER" 'WaylandEnable=true' >"$ROOT"/etc/gdm/custom.conf
 	create_symlink /usr/share/zoneinfo/"$INSTALL_TZ" "$ROOT/etc/localtime"
 	# shellcheck disable=SC2016
 	artix-chroot "$ROOT" bash -c '(id -u -- "$1" || useradd --create-home -- "$1") && locale-gen &&
@@ -205,31 +231,62 @@ usermod --append --groups wheel --shell /bin/bash -- "$1"' bash "$INSTALL_USER"
 	create_symlink ../seatd "$ROOT"/etc/dinit.d/boot.d/seatd
 	create_symlink ../dbus "$ROOT"/etc/dinit.d/boot.d/dbus
 	create_symlink ../gdm "$ROOT"/etc/dinit.d/boot.d/gdm
+	create_symlink ../qemu-ga "$ROOT"/etc/dinit.d/boot.d/qemu-ga
 	create_symlink nvim "$ROOT"/usr/bin/vi
 	create_symlink nvim "$ROOT"/usr/bin/vim
 
 	print "Creating initramfs image with dracut"
+	print_raw 'add_dracutmodules+=" dmsquash-live dm udev-rules kernel-modules kernel-modules-extra "' 'install_items+=" /usr/bin/lsblk /usr/bin/lsmod /usr/bin/lspci /usr/bin/lsusb "' >"$ROOT"/etc/dracut.conf.d/02-squashfs.conf
 	artix-chroot "$ROOT" bash - <update-dracut
 
 	print "Creating ext4 filesystem image, this may take a while"
 	delete_file "$ROOTFS"
 	# creates a ext4 image of the root directory, excluding the boot directory
-	tar --directory "$ROOT" --exclude boot --verbose --one-file-system --create \
-		--xattrs --acls --numeric-owner --preserve-permissions --xattrs --xattrs-include=* --acls --atime-preserve . 2>/tmp/tar.log |
-		mkfs.ext4 -d - -- "$ROOTFS" 8G
+	tar --directory "$ROOT" --exclude /boot --one-file-system --create \
+		--xattrs --acls --numeric-owner --preserve-permissions --xattrs --xattrs-include=* --acls --atime-preserve . |
+		mkfs.ext4 -d - -- "$ROOTFS" 10G
 	resize2fs -M -- "$ROOTFS" # shrink the filesystem to the minimum size
 
 	print "Creating squashfs filesystem image, this may take a while"
 	SQUASHFS_DIR="$BOOT/LiveOS"
 	SQUASHFS_PATH="$SQUASHFS_DIR/squashfs.img"
 	create_dir "$SQUASHFS_DIR"
-	mksquashfs - "$SQUASHFS_PATH" -p '/ d 0755 0 0' -p '/LiveOS/ d 0755 0 0' -p '/LiveOS/rootfs.img f 0600 0 0 cat' -noappend -no-recovery <"$ROOTFS"
-fi
+	mksquashfs - "$SQUASHFS_PATH" -p '/ d 0755 0 0' -p '/LiveOS/ d 0755 0 0' -p '/LiveOS/rootfs.img f 0644 0 0 cat' -noappend -no-recovery <"$ROOTFS"
 
-print "Generating GRUB configuration"
-create_dir "$BOOT"/boot
-create_dir "$BOOT"/boot/grub
-awk -v VOLID="$VOLID" '{gsub(/\$VOLID/, VOLID);}1' grub.cfg >"$BOOT"/boot/grub/grub.cfg
+	print "Generating GRUB configuration"
+	create_dir "$BOOT"/boot
+	create_dir "$BOOT"/boot/grub
+	awk -v VOLID="$VOLID" '{gsub(/\$VOLID/, VOLID);}1' grub.cfg >"$BOOT"/boot/grub/grub.cfg
 
-print "Creating ISO"
-grub-mkrescue -o "$ISO" "$BOOT" -- -volid "$VOLID"
+	print "Creating ISO"
+	grub-mkrescue -o "$ISO" "$BOOT" -- -volid "$VOLID"
+
+	print "Output ISO: $ISO"
+}
+function main() {
+	if [[ "$#" == "0" ]]; then
+		print "Available commands:"
+		print "clean: Remove generated files"
+		print "make: Create the recovery ISO"
+		return 0
+	fi
+	if [[ "$#" != "1" ]]; then
+		error "Invalid usage" >&2
+		return 1
+	fi
+	case "$1" in
+	clean)
+		clean
+		return "$?"
+		;;
+	make)
+		make
+		return "$?"
+		;;
+	*)
+		error "Invalid command" >&2
+		return 1
+		;;
+	esac
+}
+main "$@"
